#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : musl
Version  : 1.1.15
Release  : 3
URL      : https://www.musl-libc.org/releases/musl-1.1.15.tar.gz
Source0  : https://www.musl-libc.org/releases/musl-1.1.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: musl-bin
Requires: musl-lib
Patch1: 0001-Don-t-use-cross-compile-ar-or-ranlib.patch

%description
musl libc
musl, pronounced like the word "mussel", is an MIT-licensed
implementation of the standard C library targetting the Linux syscall
API, suitable for use in a wide range of deployment environments. musl
offers efficient static and dynamic linking support, lightweight code
and low runtime overhead, strong fail-safe guarantees under correct
usage, and correctness in the sense of standards conformance and
safety. musl is built on the principle that these goals are best
achieved through simple code that is easy to understand and maintain.

%package bin
Summary: bin components for the musl package.
Group: Binaries

%description bin
bin components for the musl package.


%package lib
Summary: lib components for the musl package.
Group: Libraries

%description lib
lib components for the musl package.


%prep
%setup -q -n musl-1.1.15
%patch1 -p1

%build
export LANG=C
%configure --disable-static --target=x86_64-generic-linux --prefix=/usr/lib64/musl --exec-prefix=/usr --includedir=/usr/lib64/musl/ --libdir=/usr/lib64/musl/lib64
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/lib/ld-musl-x86_64.so.1
/usr/lib64/musl/aio.h
/usr/lib64/musl/alloca.h
/usr/lib64/musl/ar.h
/usr/lib64/musl/arpa/ftp.h
/usr/lib64/musl/arpa/inet.h
/usr/lib64/musl/arpa/nameser.h
/usr/lib64/musl/arpa/nameser_compat.h
/usr/lib64/musl/arpa/telnet.h
/usr/lib64/musl/arpa/tftp.h
/usr/lib64/musl/assert.h
/usr/lib64/musl/bits/alltypes.h
/usr/lib64/musl/bits/endian.h
/usr/lib64/musl/bits/errno.h
/usr/lib64/musl/bits/fcntl.h
/usr/lib64/musl/bits/fenv.h
/usr/lib64/musl/bits/float.h
/usr/lib64/musl/bits/io.h
/usr/lib64/musl/bits/ioctl.h
/usr/lib64/musl/bits/ioctl_fix.h
/usr/lib64/musl/bits/ipc.h
/usr/lib64/musl/bits/limits.h
/usr/lib64/musl/bits/mman.h
/usr/lib64/musl/bits/msg.h
/usr/lib64/musl/bits/poll.h
/usr/lib64/musl/bits/posix.h
/usr/lib64/musl/bits/reg.h
/usr/lib64/musl/bits/resource.h
/usr/lib64/musl/bits/sem.h
/usr/lib64/musl/bits/setjmp.h
/usr/lib64/musl/bits/shm.h
/usr/lib64/musl/bits/signal.h
/usr/lib64/musl/bits/socket.h
/usr/lib64/musl/bits/stat.h
/usr/lib64/musl/bits/statfs.h
/usr/lib64/musl/bits/stdarg.h
/usr/lib64/musl/bits/stdint.h
/usr/lib64/musl/bits/syscall.h
/usr/lib64/musl/bits/termios.h
/usr/lib64/musl/bits/user.h
/usr/lib64/musl/byteswap.h
/usr/lib64/musl/complex.h
/usr/lib64/musl/cpio.h
/usr/lib64/musl/crypt.h
/usr/lib64/musl/ctype.h
/usr/lib64/musl/dirent.h
/usr/lib64/musl/dlfcn.h
/usr/lib64/musl/elf.h
/usr/lib64/musl/endian.h
/usr/lib64/musl/err.h
/usr/lib64/musl/errno.h
/usr/lib64/musl/fcntl.h
/usr/lib64/musl/features.h
/usr/lib64/musl/fenv.h
/usr/lib64/musl/float.h
/usr/lib64/musl/fmtmsg.h
/usr/lib64/musl/fnmatch.h
/usr/lib64/musl/ftw.h
/usr/lib64/musl/getopt.h
/usr/lib64/musl/glob.h
/usr/lib64/musl/grp.h
/usr/lib64/musl/iconv.h
/usr/lib64/musl/ifaddrs.h
/usr/lib64/musl/inttypes.h
/usr/lib64/musl/iso646.h
/usr/lib64/musl/langinfo.h
/usr/lib64/musl/lastlog.h
/usr/lib64/musl/lib64/Scrt1.o
/usr/lib64/musl/lib64/crt1.o
/usr/lib64/musl/lib64/crti.o
/usr/lib64/musl/lib64/crtn.o
/usr/lib64/musl/lib64/musl-gcc.specs
/usr/lib64/musl/lib64/rcrt1.o
/usr/lib64/musl/libgen.h
/usr/lib64/musl/libintl.h
/usr/lib64/musl/limits.h
/usr/lib64/musl/link.h
/usr/lib64/musl/locale.h
/usr/lib64/musl/malloc.h
/usr/lib64/musl/math.h
/usr/lib64/musl/memory.h
/usr/lib64/musl/mntent.h
/usr/lib64/musl/monetary.h
/usr/lib64/musl/mqueue.h
/usr/lib64/musl/net/ethernet.h
/usr/lib64/musl/net/if.h
/usr/lib64/musl/net/if_arp.h
/usr/lib64/musl/net/route.h
/usr/lib64/musl/netdb.h
/usr/lib64/musl/netinet/ether.h
/usr/lib64/musl/netinet/icmp6.h
/usr/lib64/musl/netinet/if_ether.h
/usr/lib64/musl/netinet/igmp.h
/usr/lib64/musl/netinet/in.h
/usr/lib64/musl/netinet/in_systm.h
/usr/lib64/musl/netinet/ip.h
/usr/lib64/musl/netinet/ip6.h
/usr/lib64/musl/netinet/ip_icmp.h
/usr/lib64/musl/netinet/tcp.h
/usr/lib64/musl/netinet/udp.h
/usr/lib64/musl/netpacket/packet.h
/usr/lib64/musl/nl_types.h
/usr/lib64/musl/paths.h
/usr/lib64/musl/poll.h
/usr/lib64/musl/pthread.h
/usr/lib64/musl/pty.h
/usr/lib64/musl/pwd.h
/usr/lib64/musl/regex.h
/usr/lib64/musl/resolv.h
/usr/lib64/musl/sched.h
/usr/lib64/musl/scsi/scsi.h
/usr/lib64/musl/scsi/scsi_ioctl.h
/usr/lib64/musl/scsi/sg.h
/usr/lib64/musl/search.h
/usr/lib64/musl/semaphore.h
/usr/lib64/musl/setjmp.h
/usr/lib64/musl/shadow.h
/usr/lib64/musl/signal.h
/usr/lib64/musl/spawn.h
/usr/lib64/musl/stdalign.h
/usr/lib64/musl/stdarg.h
/usr/lib64/musl/stdbool.h
/usr/lib64/musl/stdc-predef.h
/usr/lib64/musl/stddef.h
/usr/lib64/musl/stdint.h
/usr/lib64/musl/stdio.h
/usr/lib64/musl/stdio_ext.h
/usr/lib64/musl/stdlib.h
/usr/lib64/musl/stdnoreturn.h
/usr/lib64/musl/string.h
/usr/lib64/musl/strings.h
/usr/lib64/musl/stropts.h
/usr/lib64/musl/sys/acct.h
/usr/lib64/musl/sys/auxv.h
/usr/lib64/musl/sys/cachectl.h
/usr/lib64/musl/sys/dir.h
/usr/lib64/musl/sys/epoll.h
/usr/lib64/musl/sys/errno.h
/usr/lib64/musl/sys/eventfd.h
/usr/lib64/musl/sys/fanotify.h
/usr/lib64/musl/sys/fcntl.h
/usr/lib64/musl/sys/file.h
/usr/lib64/musl/sys/fsuid.h
/usr/lib64/musl/sys/inotify.h
/usr/lib64/musl/sys/io.h
/usr/lib64/musl/sys/ioctl.h
/usr/lib64/musl/sys/ipc.h
/usr/lib64/musl/sys/kd.h
/usr/lib64/musl/sys/klog.h
/usr/lib64/musl/sys/mman.h
/usr/lib64/musl/sys/mount.h
/usr/lib64/musl/sys/msg.h
/usr/lib64/musl/sys/mtio.h
/usr/lib64/musl/sys/param.h
/usr/lib64/musl/sys/personality.h
/usr/lib64/musl/sys/poll.h
/usr/lib64/musl/sys/prctl.h
/usr/lib64/musl/sys/procfs.h
/usr/lib64/musl/sys/ptrace.h
/usr/lib64/musl/sys/quota.h
/usr/lib64/musl/sys/reboot.h
/usr/lib64/musl/sys/reg.h
/usr/lib64/musl/sys/resource.h
/usr/lib64/musl/sys/select.h
/usr/lib64/musl/sys/sem.h
/usr/lib64/musl/sys/sendfile.h
/usr/lib64/musl/sys/shm.h
/usr/lib64/musl/sys/signal.h
/usr/lib64/musl/sys/signalfd.h
/usr/lib64/musl/sys/socket.h
/usr/lib64/musl/sys/soundcard.h
/usr/lib64/musl/sys/stat.h
/usr/lib64/musl/sys/statfs.h
/usr/lib64/musl/sys/statvfs.h
/usr/lib64/musl/sys/stropts.h
/usr/lib64/musl/sys/swap.h
/usr/lib64/musl/sys/syscall.h
/usr/lib64/musl/sys/sysinfo.h
/usr/lib64/musl/sys/syslog.h
/usr/lib64/musl/sys/sysmacros.h
/usr/lib64/musl/sys/termios.h
/usr/lib64/musl/sys/time.h
/usr/lib64/musl/sys/timeb.h
/usr/lib64/musl/sys/timerfd.h
/usr/lib64/musl/sys/times.h
/usr/lib64/musl/sys/timex.h
/usr/lib64/musl/sys/ttydefaults.h
/usr/lib64/musl/sys/types.h
/usr/lib64/musl/sys/ucontext.h
/usr/lib64/musl/sys/uio.h
/usr/lib64/musl/sys/un.h
/usr/lib64/musl/sys/user.h
/usr/lib64/musl/sys/utsname.h
/usr/lib64/musl/sys/vfs.h
/usr/lib64/musl/sys/vt.h
/usr/lib64/musl/sys/wait.h
/usr/lib64/musl/sys/xattr.h
/usr/lib64/musl/syscall.h
/usr/lib64/musl/sysexits.h
/usr/lib64/musl/syslog.h
/usr/lib64/musl/tar.h
/usr/lib64/musl/termios.h
/usr/lib64/musl/tgmath.h
/usr/lib64/musl/threads.h
/usr/lib64/musl/time.h
/usr/lib64/musl/uchar.h
/usr/lib64/musl/ucontext.h
/usr/lib64/musl/ulimit.h
/usr/lib64/musl/unistd.h
/usr/lib64/musl/utime.h
/usr/lib64/musl/utmp.h
/usr/lib64/musl/utmpx.h
/usr/lib64/musl/values.h
/usr/lib64/musl/wait.h
/usr/lib64/musl/wchar.h
/usr/lib64/musl/wctype.h
/usr/lib64/musl/wordexp.h

%files bin
%defattr(-,root,root,-)
/usr/bin/musl-gcc

%files lib
%defattr(-,root,root,-)
/usr/lib64/musl/lib64/libc.so
