#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : musl
Version  : 1.1.15
Release  : 1
URL      : https://www.musl-libc.org/releases/musl-1.1.15.tar.gz
Source0  : https://www.musl-libc.org/releases/musl-1.1.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: musl-bin
Patch1: 0001-Don-t-use-cross-compile-ar-or-ranlib.patch

%description
musl libc
musl, pronounced like the word "mussel", is an MIT-licensed
implementation of the standard C library targetting the Linux syscall
API, suitable for use in a wide range of deployment environments. musl
offers efficient static and dynamic linking support, lightweight code
and low runtime overhead, strong fail-safe guarantees under correct
usage, and correctness in the sense of standards conformance and
safety. musl is built on the principle that these goals are best
achieved through simple code that is easy to understand and maintain.

%package bin
Summary: bin components for the musl package.
Group: Binaries

%description bin
bin components for the musl package.


%package dev
Summary: dev components for the musl package.
Group: Development
Requires: musl-bin
Provides: musl-devel

%description dev
dev components for the musl package.


%prep
%setup -q -n musl-1.1.15
%patch1 -p1

%build
export LANG=C
%configure --disable-static --target=x86_64-generic-linux
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/lib/ld-musl-x86_64.so.1
/usr/lib64/Scrt1.o
/usr/lib64/crt1.o
/usr/lib64/crti.o
/usr/lib64/crtn.o
/usr/lib64/musl-gcc.specs
/usr/lib64/rcrt1.o

%files bin
%defattr(-,root,root,-)
/usr/bin/musl-gcc

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/arpa/ftp.h
/usr/include/arpa/inet.h
/usr/include/arpa/nameser.h
/usr/include/arpa/nameser_compat.h
/usr/include/arpa/telnet.h
/usr/include/arpa/tftp.h
/usr/include/bits/alltypes.h
/usr/include/bits/endian.h
/usr/include/bits/errno.h
/usr/include/bits/fcntl.h
/usr/include/bits/fenv.h
/usr/include/bits/float.h
/usr/include/bits/io.h
/usr/include/bits/ioctl.h
/usr/include/bits/ioctl_fix.h
/usr/include/bits/ipc.h
/usr/include/bits/limits.h
/usr/include/bits/mman.h
/usr/include/bits/msg.h
/usr/include/bits/poll.h
/usr/include/bits/posix.h
/usr/include/bits/reg.h
/usr/include/bits/resource.h
/usr/include/bits/sem.h
/usr/include/bits/setjmp.h
/usr/include/bits/shm.h
/usr/include/bits/signal.h
/usr/include/bits/socket.h
/usr/include/bits/stat.h
/usr/include/bits/statfs.h
/usr/include/bits/stdarg.h
/usr/include/bits/stdint.h
/usr/include/bits/syscall.h
/usr/include/bits/termios.h
/usr/include/bits/user.h
/usr/include/net/ethernet.h
/usr/include/net/if.h
/usr/include/net/if_arp.h
/usr/include/net/route.h
/usr/include/netinet/ether.h
/usr/include/netinet/icmp6.h
/usr/include/netinet/if_ether.h
/usr/include/netinet/igmp.h
/usr/include/netinet/in.h
/usr/include/netinet/in_systm.h
/usr/include/netinet/ip.h
/usr/include/netinet/ip6.h
/usr/include/netinet/ip_icmp.h
/usr/include/netinet/tcp.h
/usr/include/netinet/udp.h
/usr/include/netpacket/packet.h
/usr/include/scsi/scsi.h
/usr/include/scsi/scsi_ioctl.h
/usr/include/scsi/sg.h
/usr/include/sys/acct.h
/usr/include/sys/auxv.h
/usr/include/sys/cachectl.h
/usr/include/sys/dir.h
/usr/include/sys/epoll.h
/usr/include/sys/errno.h
/usr/include/sys/eventfd.h
/usr/include/sys/fanotify.h
/usr/include/sys/fcntl.h
/usr/include/sys/file.h
/usr/include/sys/fsuid.h
/usr/include/sys/inotify.h
/usr/include/sys/io.h
/usr/include/sys/ioctl.h
/usr/include/sys/ipc.h
/usr/include/sys/kd.h
/usr/include/sys/klog.h
/usr/include/sys/mman.h
/usr/include/sys/mount.h
/usr/include/sys/msg.h
/usr/include/sys/mtio.h
/usr/include/sys/param.h
/usr/include/sys/personality.h
/usr/include/sys/poll.h
/usr/include/sys/prctl.h
/usr/include/sys/procfs.h
/usr/include/sys/ptrace.h
/usr/include/sys/quota.h
/usr/include/sys/reboot.h
/usr/include/sys/reg.h
/usr/include/sys/resource.h
/usr/include/sys/select.h
/usr/include/sys/sem.h
/usr/include/sys/sendfile.h
/usr/include/sys/shm.h
/usr/include/sys/signal.h
/usr/include/sys/signalfd.h
/usr/include/sys/socket.h
/usr/include/sys/soundcard.h
/usr/include/sys/stat.h
/usr/include/sys/statfs.h
/usr/include/sys/statvfs.h
/usr/include/sys/stropts.h
/usr/include/sys/swap.h
/usr/include/sys/syscall.h
/usr/include/sys/sysinfo.h
/usr/include/sys/syslog.h
/usr/include/sys/sysmacros.h
/usr/include/sys/termios.h
/usr/include/sys/time.h
/usr/include/sys/timeb.h
/usr/include/sys/timerfd.h
/usr/include/sys/times.h
/usr/include/sys/timex.h
/usr/include/sys/ttydefaults.h
/usr/include/sys/types.h
/usr/include/sys/ucontext.h
/usr/include/sys/uio.h
/usr/include/sys/un.h
/usr/include/sys/user.h
/usr/include/sys/utsname.h
/usr/include/sys/vfs.h
/usr/include/sys/vt.h
/usr/include/sys/wait.h
/usr/include/sys/xattr.h
/usr/lib64/*.so
